### ISSUE TITLE
installing relax-theme

### ISSUE THREAD

**Issue by tleonard2** [rainlab/relax-theme#1]
I have installed the relax-theme on my test platform. All other themes activate correctly. When i activate this theme, i get this error: 

Class name is not registered for the component session. Check the component plugin.
/Users/tleonard2/Sites/octobercms/modules/cms/Classes/ComponentManager.php line 200

any ideas?

Theresa

**Comment by daftspunk** [comment]
Make sure you have these accompanying plugins installed too:

```
- RainLab.User
- RainLab.Blog
- RainLab.Pages
```

**Comment by tleonard2** [comment]
that was fast. thanks. that fixed the error. I watched the new video on this but had hoped for more info on setting up the user pages vs. using them from the front end. Like setting up the sidebars etc. Did i miss this somewhere?

**Comment by daftspunk** [comment]
We should have more tutorials on the way soon

**Comment by subha1129** [comment]
Class name is not registered for the component "twitterStatuses". Check the component plugin.

can anyone solve this error plz..
