### ISSUE TITLE
{% if post('register') %} should be {% if get('register') %}

### ISSUE THREAD

**Issue by KirbyFox** [rainlab/relax-theme#3]
Hi,

{% if post('register') %}

Should be

{% if get('register') %}

https://github.com/rainlab/relax-theme/blob/master/pages/account.htm

**Comment by LaravelNick** [comment]
Just install a fresh copy of October CMS with the House of Chairs theme and set Activation Mode to 'User'.

It definitely ignores the {% if post('register') %} and I never saw the message to inform me that an email had been sent.

The email was sent and I received it and that all worked fine. It's just the {% if post('register') %} bit that doesn't work.
