### ISSUE TITLE
500 error when combining assets

### ISSUE THREAD

**Issue by zoltiecodes** [rainlab/relax-theme#5]
Hi,

The theme is collapsed because it can't load a combined css file. 

I'm getting 500 error for this link: http://october.bleed.co/combine/b0ce7a90dc4b245c7ad09eb0340ca602-1482345592 

This is the combined vendor.less There is nothing in the logs...

Can anybody help me figure this out? Thanks!

**Comment by LukeTowers** [comment]
@teoni Are you still getting this error?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
