### ISSUE TITLE
Missing components?

### ISSUE THREAD

**Issue by g-gullstrand** [rainlab/relax-theme#7]
The theme seems to require a few plugins/components (is that what they are called?) that aren't included?

Ex. layout "home.htm" uses a "account" component which I don't find. Generates error: 

_**"Class name is not registered for the component "account". Check the component plugin."**_

Same for "session" & "blogPosts"

**Comment by LukeTowers** [comment]
This theme requires three separate plugins, documented in the theme.yaml: https://github.com/rainlab/relax-theme/blob/master/theme.yaml#L6-L9. How did you install it?
